### ISSUE TITLE
spelling issue!

### ISSUE THREAD

**Issue by ranjan2829** [siddhant-khisty/siddhant-khisty#1]
hello !
there's a spelling issue in line 1, it's "manager" !
so fix it !
happy to help !

**Comment by siddhant-khisty** [comment]
Nice catch. Feel free to open a PR to fix it :smile:

**Comment by siddhant-khisty** [comment]
Nice catch. Fixed :smile:

**Comment by ranjan2829** [comment]
@siddhant-khisty add one more "a" in the spelling !
